### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by josealfredo79** [irving1613/Infografia#1]
Aqui debe la infografía con su evaluación de acuerdo a la rúbrica

**Comment by josealfredo79** [comment]
Aqui nuevamente debe ir la infografía y la calificación

**Comment by irving1613** [comment]
[Irving_ZR-Infografia.pdf](https://github.com/irving1613/Infografia/files/7221299/Irving_ZR-Infografia.pdf)

**Comment by josealfredo79** [comment]
Hace falta la calificacion

**Comment by RicardoMtzSts** [comment]
buen trabajo 20/20

**Comment by josealfredo79** [comment]
Esta bien hecho..y revisado
